### ISSUE TITLE
Can't load package

### ISSUE THREAD

**Issue by gdlr** [Pakillo/rSDM#4]
Hi, when I try and download the package from 

devtools::install_github("Pakillo/rSDM")

I get the error:

Downloading GitHub repo Pakillo/rSDM@HEAD
Error: Failed to install 'rSDM' from GitHub:
  lazy-load database '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/pkgbuild/R/pkgbuild.rdb' is corrupt
In addition: Warning messages:
1: In get0(oNam, envir = ns) : restarting interrupted promise evaluation
2: In get0(oNam, envir = ns) : internal error -3 in R_decompress1

Can you please help? I'm very interested in the point to cell function in this!

**Comment by Pakillo** [comment]
Hi Gabriel,

Did you manage to install? I think it should work if you just shut down and restart R before attempting installation again (e.g. see https://github.com/lme4/lme4/issues/407)

**Comment by gdlr** [comment]
That worked! Who knew it would be so easy...!

**Comment by Pakillo** [comment]
Great. Thanks for reporting. And good luck with your analysis!
Closing
